FROM metsi/ats-short-course:latest
LABEL Description="Linux permissons patch."

ARG container_user=ats_sc_user

ENV https_proxy=$https_proxy \
    http_proxy=$http_proxy

WORKDIR ${HOME}
RUN mkdir .local && \
    chmod g+ws . .local .jupyter .cache && \
    umask 002 && \
    echo "# set umask for group rwx" >> ~/.bashrc && \
    echo "umask 002" >> ~/.bashrc && \
    echo " " >> ~/.bashrc 

# Unset proxy
ENV https_proxy= \
    http_proxy=

WORKDIR ${HOME}/short-course
