FROM metsi/ats-short-course:2025-base-latest

LABEL Description="Build TPLs"

# Versions change and we cannot set environment variables from command output.
ARG petsc_ver=3.20
ARG trilinos_ver=15-1-0
ARG amanzi_branch=amanzi-1.6

# Verify ${HOME} was set in the base image to /home/$container_user
RUN echo "Unprivileged username: `whoami`" && \
    echo "User's home directory: ${HOME}"

# Installation paths
ENV AMANZI_PREFIX=${HOME}/install
ENV AMANZI_INSTALL_DIR=${AMANZI_PREFIX}/amanzi \
    AMANZI_TPLS_BUILD_DIR=${HOME}/amanzi_builddir/tpls \
    AMANZI_TPLS_DIR=${AMANZI_PREFIX}/tpls

# TPL versions needed for LD_LIBRARY_PATH
ENV AMANZI_PETSC_LIBS=$AMANZI_TPLS_DIR/petsc-${petsc_ver}/lib \
    AMANZI_TRILINOS_LIBS=$AMANZI_TPLS_DIR/trilinos-${trilinos_ver}/lib \
    AMANZI_SEACAS_LIBS=$AMANZI_TPLS_DIR/SEACAS/lib

# Set the current working directory as the users home directory
# (creates the directory if it doesn't exist)
WORKDIR ${HOME}

# Clone the amanzi git repo.
RUN git clone https://github.com/amanzi/amanzi.git ${HOME}/amanzi

# Set the current working directory to the git repo
# and switch branches if requested.
WORKDIR ${HOME}/amanzi
RUN if [ "$amanzi_branch" != "master" ]; then \
       git checkout $amanzi_branch; \
    fi; \
    echo "Amanzi branch = $amanzi_branch"; \
    git branch --list

# Build and install the TPLs using bootstrap.sh, and remove
# the source, objects, etc. after installation to save space.
RUN echo "Building TPLs ... " && \
     ./bootstrap.sh --prefix=${AMANZI_PREFIX} \
      --parallel=4 --opt \
      --amanzi-build-dir=${HOME}/amanzi_builddir/amanzi \
      --tools-install-prefix=${AMANZI_PREFIX}/tools \
      --tpl-build-dir=${HOME}/amanzi_builddir/tpls \
      --tpl-download-dir=${HOME}/amanzi_builddir/tpls/Downloads \
      --disable-build_amanzi --disable-build_user_guide \
      --enable-shared --enable-structured --enable-silo \
      --enable-alquimia --enable-pflotran --enable-crunchtope \
      --enable-pf_clm \
      --with-mpi=/usr/local && \
    echo "Building PFLOTRAN ... " && \
     export PETSC_DIR=$AMANZI_TPLS_BUILD_DIR/petsc/petsc-3.20-source && \
     cd $AMANZI_TPLS_BUILD_DIR/pflotran/pflotran-5.0.0-source/src/pflotran && \
     make have_hdf5=1 \
      HDF5_INCLUDE=$AMANZI_TPLS_DIR/include \
      HDF5_LIB=$AMANZI_TPLS_DIR/lib \
      LIBS="-L${HDF5_LIB} -lhdf5 -lhdf5_hl -lhdf5_hl_fortran -lhdf5_fortran -lz" \
      pflotran && \
     cp -p pflotran $AMANZI_TPLS_DIR/bin/ && \
     # echo "alias pflotran='${AMANZI_TPLS_DIR}/bin/pflotran \"\$@\"'" >> ${HOME}/.bashrc &&\
    echo "Building CrunchFlow ..." && \
     cd $AMANZI_TPLS_BUILD_DIR/crunchtope/crunchtope-101221.cf938c8.0-source/source && \
     touch chkopts && \
     make FFLAGS="-w -ffree-line-length-none" && \
     cp -p CrunchTope $AMANZI_TPLS_DIR/bin/ && \
     # echo "alias CrunchTope='${AMANZI_TPLS_DIR}/bin/CrunchTope \"\$@\"'" >> ${HOME}/.bashrc && \
    #
     cd ${HOME}/amanzi && \
     git checkout master && \
     rm -r ${HOME}/amanzi_builddir

# Set the LD_LIBRARY_PATH for Amanzi builds in the next stage
ENV LD_LIBRARY_PATH=${AMANZI_TPLS_DIR}/lib:${AMANZI_PETSC_LIBS}:${AMANZI_TRILINOS_LIBS}:${AMANZI_SEACAS_LIBS}
RUN echo $LD_LIBRARY_PATH

# Set path to pick up any tools installed during bootstrap
ENV PATH=${AMANZI_TPLS_DIR}/bin:${AMANZI_PREFIX}/tools/bin:${PATH}
RUN echo "PATH: ${PATH}"
