FROM metsi/workshop:Amanzi-latest
LABEL Description="ATS CI: Build ATS in a Docker image."

# Switch to amanzi_user
USER amanzi_user

RUN echo "${AMANZI_PREFIX}"
RUN echo "${AMANZI_TPLS_DIR}"

# Arguments
ARG amanzi_branch=master
ARG ats_branch=master
ARG https_proxy=
ARG http_proxy=

# Change the Working Directory and update amanzi
WORKDIR ${HOME}/amanzi

ENV https_proxy=$https_proxy \
    http_proxy=$http_proxy

# Make sure we have updated branch information
RUN echo "Amanzi branch = $amanzi_branch"
RUN git pull
RUN git branch --list

# Checkout the branch and update it
RUN git checkout $amanzi_branch
RUN git pull
RUN git rev-parse --short HEAD

# Checkout/update the submodules
RUN git submodule update --init --recursive

WORKDIR ${HOME}/amanzi/src/physics/ats

RUN git checkout $ats_branch
RUN git pull
RUN git rev-parse --short HEAD

WORKDIR ${HOME}/amanzi/src/physics/ats/testing/ats-regression-tests

RUN git checkout master
RUN git pull
RUN git rev-parse --short HEAD

WORKDIR ${HOME}/amanzi

ENV AMANZI_SRC_DIR=${HOME}/amanzi \
    ATS_SRC_DIR=${HOME}/amanzi/src/physics/ats

RUN ./bootstrap.sh --prefix=${AMANZI_PREFIX} \
   --amanzi-build-dir=${HOME}/amanzi_builddir/ats \
   --tpl-config-file=${AMANZI_TPLS_DIR}/share/cmake/amanzi-tpl-config.cmake \
   --branch=$amanzi_branch \
   --branch_ats=$ats_branch \
   --parallel=4 \
   --opt \
   --with-mpi=/usr \
   --with-python=/opt/conda/bin/python \
   --enable-shared \
   --disable-structured \
   --disable-build_user_guide \
   --enable-geochemistry \
   --disable-amanzi_physics \
   --enable-ats_physics \
   --enable-reg_tests \
   && rm -r ${HOME}/amanzi_builddir/

# Set path to make it easier to run amanzi
# ENV PATH=/home/amanzi_user/install/bin:${PATH}
# RUN echo $PATH

# Create mount point for work on the host
# RUN mkdir /home/amanzi_user/work

# Unset proxy
ENV https_proxy= \
    http_proxy=


CMD jupyter lab --port=8888