name: Build base Ubuntu+python images for Short Course

on:
  workflow_dispatch:

# Not ready for action on push, complicated due to dependencies
# push:
#    paths:
#      - 'docker/**'
#    branches-ignore:
#      - 'main'

jobs:
  build-base-image:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
    runs-on: ${{matrix.os}}
    steps:
    - name: Check out the ATS Short Course repo
      uses: actions/checkout@v4
    - name: Extract the branch name
      id: branch
      run:
        echo "ATS_SC_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
    - name: Get runner architecture
      run: |
        if [[ ${{matrix.os}} == "ubuntu-24.04-arm" ]]; then
          echo "ARCH=arm64" >> $GITHUB_ENV
        else
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Docker build
      id: docker
      working-directory: docker
      run:
        docker build --build-arg ARCH=linux/${{env.ARCH}} --build-arg build_mpi=False -t ${{secrets.DOCKERHUB_USERNAME}}/ats-short-course:2025-base-${{env.ARCH}}-latest -f Dockerfile-Workshop-Base .
    - name: Docker push
      working-directory: docker
      run:
        docker push ${{secrets.DOCKERHUB_USERNAME}}/ats-short-course:2025-base-${{env.ARCH}}-latest
  fix-manifest:
    runs-on: ubuntu-latest
    needs: build-base-image
    if: success()
    steps:
      - name: Check out the ATS Short Course repo
        uses: actions/checkout@v4
      - name: Set environment variables
        run:
          echo "AMANZI_BRANCH_TAG=$(echo $GITHUB_REF_NAME | sed -e 's/\//--/g')" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Pull images (remove with artifacts??)
        run: |
          docker pull ${{secrets.DOCKERHUB_USERNAME}}/ats-short-course:2025-base-arm64-latest
          docker pull ${{secrets.DOCKERHUB_USERNAME}}/ats-short-course:2025-base-amd64-latest
      - name: Edit manifest
        run: |
          docker manifest create ${{secrets.DOCKERHUB_USERNAME}}/ats-short-course:2025-base-latest \
            --amend ${{secrets.DOCKERHUB_USERNAME}}/ats-short-course:2025-base-arm64-latest \
            --amend ${{secrets.DOCKERHUB_USERNAME}}/ats-short-course:2025-base-amd64-latest 
          docker manifest push ${{secrets.DOCKERHUB_USERNAME}}/ats-short-course:2025-base-latest



    
    
      