name: Build base Ubuntu+python images for Short Course

on:
  workflow_dispatch:
  push:
    paths:
      - 'docker/**'
    branches-ignore:
      - 'master'
      - 'main'

jobs:
  build-base-image:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
    runs-on: ${{matrix.os}}
    steps:
    - name: Check out the ATS Short Course repo
      uses: actions/checkout@v4
    - name: Extract the branch name
      id: branch
      run:
        echo "ATS_SC_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
    - name: Get runner architecture
      run:
        if [[ ${{matrix.os}} == "ubuntu-24.04-arm" ]]; then
          echo "ARCH=arm64" >> $GITHUB_ENV
        else
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Docker build
      id: docker
      working-directory: docker
      run: |
        docker build --build-arg ARCH=linux/${{env.ARCH}} \
        --build-arg build_mpi=False \
        -t metsi/ats_short_course:2025-base-${{env.ARCH}}-latest \
        -f Dockerfile-Workshop-Base .
    - name: Docker push
      working-directory: Docker
      run:
        docker push ${{secrets.DOCKERHUB_USERNAME}}/ats-short-course:2025-base-${{env.ARCH}}-latest



    
    
      